In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
from pandas import DataFrame
import numpy as np
import matplotlib.pyplot as plt
import math 
from pandas.core import shared_docs
import scipy.stats

# visualization
import seaborn as sns

# similarity
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
rating = pd.read_csv("/content/drive/MyDrive/DATA.ML.360/ratings.csv")
movies = pd.read_csv("/content/drive/MyDrive/DATA.ML.360/movies.csv")

In [ ]:
df = pd.merge(rating, movies, on='movieId', how='inner')
df.head()

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,847434962,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,7,1,4.5,1106635946,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
3,15,1,2.5,1510577970,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
4,17,1,4.5,1305696483,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy

In [ ]:
# Create user-item matrix
matrix_item = df.pivot_table(index='title', columns='userId', values='rating')
matrix_item.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Round Midnight (1986),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Salem's Lot (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Til There Was You (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Normalize user-item matrix
matrix_item_norm = matrix_item.subtract(matrix_item.mean(axis=1), axis = 0)
matrix_item_norm

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Round Midnight (1986),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Salem's Lot (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Til There Was You (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.136364,NaN,NaN,NaN,NaN,0.636364,NaN,NaN
xXx (2002),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.770833,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.729167,NaN,-0.770833
xXx: State of the Union (2005),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.500000
¡Three Amigos! (1986),0.865385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
À nous la liberté (Freedom for Us) (1931),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
item_similarity_pearson = matrix_item_norm.T.corr()
item_similarity_pearson.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Round Midnight (1986),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Salem's Lot (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Til There Was You (1997),NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_item_similarity_cosine = pd.DataFrame(cosine_similarity(matrix_item_norm.fillna(0.0000001)))
df_item_similarity_cosine

,0,1,2,3,4,5,6,7,8,9,...,9709,9710,9711,9712,9713,9714,9715,9716,9717,9718
0,1.000000e+00,9.983580e-01,9.975353e-01,9.983580e-01,1.739262e-06,9.983580e-01,4.849432e-07,9.983580e-01,9.979238e-04,2.040971e-06,...,9.983580e-01,1.167014e-03,6.254965e-03,9.991786e-01,9.983580e-01,6.452161e-07,6.738618e-03,2.026347e-02,5.005109e-07,9.983580e-01
1,9.983580e-01,1.000000e+00,9.991786e-01,9.983580e-01,1.739262e-06,9.983580e-01,4.849432e-07,9.983580e-01,3.393780e-07,2.040971e-06,...,9.983580e-01,1.121121e-06,2.273477e-06,9.975353e-01,9.983580e-01,6.452161e-07,5.113676e-07,2.447532e-06,5.005109e-07,9.983580e-01
2,9.975353e-01,9.991786e-01,1.000000e+00,9.975353e-01,1.737824e-06,9.975353e-01,-2.651919e-03,9.975353e-01,3.390579e-07,2.039256e-06,...,9.975353e-01,1.120175e-06,2.271591e-06,9.967105e-01,9.975353e-01,6.446464e-07,5.109131e-07,2.445488e-06,5.000631e-07,9.975353e-01
3,9.983580e-01,9.983580e-01,9.975353e-01,1.000000e+00,-2.865167e-02,9.983580e-01,4.849432e-07,9.983580e-01,3.393780e-07,2.040971e-06,...,9.983580e-01,1.121121e-06,2.273477e-06,9.975353e-01,9.983580e-01,6.452161e-07,5.113676e-07,2.447532e-06,5.005109e-07,9.983580e-01
4,1.739262e-06,1.739262e-06,1.737824e-06,-2.865167e-02,1.000000e+00,1.739262e-06,8.447929e-13,1.739262e-06,5.911677e-13,3.555564e-12,...,1.739262e-06,1.953092e-12,3.960655e-12,1.737824e-06,1.739262e-06,1.123979e-12,8.908075e-13,4.263854e-12,8.718899e-13,1.739262e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9714,6.452161e-07,6.452161e-07,6.446464e-07,6.452161e-07,1.123979e-12,6.452161e-07,6.069914e-02,-1.498230e-03,-7.527707e-02,2.947369e-02,...,6.452161e-07,7.242529e-13,1.469123e-12,6.446464e-07,6.452161e-07,1.000000e+00,3.784586e-02,1.581409e-12,-3.410932e-02,6.452161e-07
9715,6.738618e-03,5.113676e-07,5.109131e-07,5.113676e-07,8.908075e-13,5.113676e-07,-3.527099e-03,5.113676e-07,1.558884e-01,2.511178e-01,...,1.547995e-02,-2.067568e-01,-4.854178e-03,4.739290e-03,5.113676e-07,3.784586e-02,1.000000e+00,2.449297e-01,1.854832e-02,5.113676e-07
9716,2.026347e-02,2.447532e-06,2.445488e-06,2.447532e-06,4.263854e-12,2.447532e-06,1.188653e-12,2.447532e-06,1.107823e-01,5.003227e-12,...,2.447532e-06,-2.014023e-01,7.715174e-02,2.028013e-02,2.447532e-06,1.581409e-12,2.449297e-01,1.000000e+00,1.226683e-12,2.447532e-06
9717,5.005109e-07,5.005109e-07,5.000631e-07,5.005109e-07,8.718899e-13,5.005109e-07,1.683583e-02,1.156187e-03,4.333034e-02,1.292903e-01,...,1.156187e-03,5.617753e-13,1.139610e-12,5.000631e-07,5.005109e-07,-3.410932e-02,1.854832e-02,1.226683e-12,1.000000e+00,5.005109e-07
9718,9.983580e-01,9.983580e-01,9.975353e-01,9.983580e-01,1.739262e-06,9.983580e-01,4.849432e-07,9.983580e-01,3.393780e-07,2.040971e-06,...,9.983580e-01,1.121121e-06,2.273477e-06,9.975353e-01,9.983580e-01,6.452161e-07,5.113676e-07,2.447532e-06,5.005109e-07,1.000000e+00

In [ ]:
df_item_similarity_cosine.columns = item_similarity_pearson.columns
df_item_similarity_cosine.index = item_similarity_pearson.index

In [ ]:
df_item_similarity_cosine

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),1.000000e+00,9.983580e-01,9.975353e-01,9.983580e-01,1.739262e-06,9.983580e-01,4.849432e-07,9.983580e-01,9.979238e-04,2.040971e-06,...,9.983580e-01,1.167014e-03,6.254965e-03,9.991786e-01,9.983580e-01,6.452161e-07,6.738618e-03,2.026347e-02,5.005109e-07,9.983580e-01
'Hellboy': The Seeds of Creation (2004),9.983580e-01,1.000000e+00,9.991786e-01,9.983580e-01,1.739262e-06,9.983580e-01,4.849432e-07,9.983580e-01,3.393780e-07,2.040971e-06,...,9.983580e-01,1.121121e-06,2.273477e-06,9.975353e-01,9.983580e-01,6.452161e-07,5.113676e-07,2.447532e-06,5.005109e-07,9.983580e-01
'Round Midnight (1986),9.975353e-01,9.991786e-01,1.000000e+00,9.975353e-01,1.737824e-06,9.975353e-01,-2.651919e-03,9.975353e-01,3.390579e-07,2.039256e-06,...,9.975353e-01,1.120175e-06,2.271591e-06,9.967105e-01,9.975353e-01,6.446464e-07,5.109131e-07,2.445488e-06,5.000631e-07,9.975353e-01
'Salem's Lot (2004),9.983580e-01,9.983580e-01,9.975353e-01,1.000000e+00,-2.865167e-02,9.983580e-01,4.849432e-07,9.983580e-01,3.393780e-07,2.040971e-06,...,9.983580e-01,1.121121e-06,2.273477e-06,9.975353e-01,9.983580e-01,6.452161e-07,5.113676e-07,2.447532e-06,5.005109e-07,9.983580e-01
'Til There Was You (1997),1.739262e-06,1.739262e-06,1.737824e-06,-2.865167e-02,1.000000e+00,1.739262e-06,8.447929e-13,1.739262e-06,5.911677e-13,3.555564e-12,...,1.739262e-06,1.953092e-12,3.960655e-12,1.737824e-06,1.739262e-06,1.123979e-12,8.908075e-13,4.263854e-12,8.718899e-13,1.739262e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),6.452161e-07,6.452161e-07,6.446464e-07,6.452161e-07,1.123979e-12,6.452161e-07,6.069914e-02,-1.498230e-03,-7.527707e-02,2.947369e-02,...,6.452161e-07,7.242529e-13,1.469123e-12,6.446464e-07,6.452161e-07,1.000000e+00,3.784586e-02,1.581409e-12,-3.410932e-02,6.452161e-07
xXx (2002),6.738618e-03,5.113676e-07,5.109131e-07,5.113676e-07,8.908075e-13,5.113676e-07,-3.527099e-03,5.113676e-07,1.558884e-01,2.511178e-01,...,1.547995e-02,-2.067568e-01,-4.854178e-03,4.739290e-03,5.113676e-07,3.784586e-02,1.000000e+00,2.449297e-01,1.854832e-02,5.113676e-07
xXx: State of the Union (2005),2.026347e-02,2.447532e-06,2.445488e-06,2.447532e-06,4.263854e-12,2.447532e-06,1.188653e-12,2.447532e-06,1.107823e-01,5.003227e-12,...,2.447532e-06,-2.014023e-01,7.715174e-02,2.028013e-02,2.447532e-06,1.581409e-12,2.449297e-01,1.000000e+00,1.226683e-12,2.447532e-06
¡Three Amigos! (1986),5.005109e-07,5.005109e-07,5.000631e-07,5.005109e-07,8.718899e-13,5.005109e-07,1.683583e-02,1.156187e-03,4.333034e-02,1.292903e-01,...,1.156187e-03,5.617753e-13,1.139610e-12,5.000631e-07,5.005109e-07,-3.410932e-02,1.854832e-02,1.226683e-12,1.000000e+00,5.005109e-07
À nous la liberté (Freedom for Us) (1931),9.983580e-01,9.983580e-01,9.975353e-01,9.983580e-01,1.739262e-06,9.983580e-01,4.849432e-07,9.983580e-01,3.393780e-07,2.040971e-06,...,9.983580e-01,1.121121e-06,2.273477e-06,9.975353e-01,9.983580e-01,6.452161e-07,5.113676e-07,2.447532e-06,5.005109e-07,1.000000e+00

In [ ]:
# Item-based recommendation function
def item_based_rec(picked_userid, number_of_similar_items, number_of_recommendations):
  import operator
  # Movies that the target user has not watched
  picked_userid_unwatched = pd.DataFrame(matrix_item_norm[picked_userid].isna()).reset_index()
  picked_userid_unwatched = picked_userid_unwatched[picked_userid_unwatched[picked_userid]==True]['title'].values.tolist()

  # Movies that the target user has watched
  picked_userid_watched = pd.DataFrame(matrix_item_norm[picked_userid].dropna(axis=0, how='all')\
                            .sort_values(ascending=False))\
                            .reset_index()\
                            .rename(columns={picked_userid:'rating'})
  
  # Dictionary to save the unwatched movie and predicted rating pair
  rating_prediction ={}  

  # Loop through unwatched movies          
  for picked_movie in picked_userid_unwatched: 
    # Calculate the similarity score of the picked movie iwth other movies
    # picked_movie_similarity_score = item_similarity_pearson[[picked_movie]].reset_index().rename(columns={picked_movie:'similarity_score'})
    picked_movie_similarity_score = df_item_similarity_cosine[[picked_movie]].reset_index().rename(columns={picked_movie:'similarity_score'})

    # Rank the similarities between the picked user watched movie and the picked unwatched movie.
    picked_userid_watched_similarity = pd.merge(left=picked_userid_watched, 
                                                right=picked_movie_similarity_score, 
                                                on='title', 
                                                how='inner')\
                                        .sort_values('similarity_score', ascending=False)[:number_of_similar_items]

    # Calculate the predicted rating using weighted average of similarity scores and the ratings from user 1
    # predicted_rating = round(np.average(picked_userid_watched_similarity['rating']),6)
    predicted_rating = round(np.average(picked_userid_watched_similarity['rating'], 
                                        weights=picked_userid_watched_similarity['similarity_score']), 6)
    
    # Save the predicted rating in the dictionary
    rating_prediction[picked_movie] = predicted_rating
    # Return the top recommended movies
  return sorted(rating_prediction.items(), key=operator.itemgetter(1), reverse=True)[:number_of_recommendations]

# Get recommendations
recommended_movie = item_based_rec(picked_userid=1, number_of_similar_items=5, number_of_recommendations =20)
recommended_movie

[('Valerian and the City of a Thousand Planets (2017)', 1.631481),
 ('Firewalker (1986)', 1.617744),
 ('Fist of Fury (Chinese Connection, The) (Jing wu men) (1972)', 1.617715),
 ('Crow: Salvation, The (2000)', 1.615339),
 ('Baby... Secret of the Lost Legend (1985)', 1.599267),
 ('Ant Bully, The (2006)', 1.595968),
 ('Curse of the Jade Scorpion, The (2001)', 1.59194),
 ('Deuce Bigalow: European Gigolo (2005)', 1.579533),
 ('Jackass: The Movie (2002)', 1.577884),
 ('Soul Plane (2004)', 1.575613),
 ('Swan Princess, The (1994)', 1.565838),
 ('Hustle & Flow (2005)', 1.564681),
 ('Doctor Who: Last Christmas (2014)', 1.561683),
 ('Doctor Who: The Doctor, the Widow and the Wardrobe (2011)', 1.561683),
 ('Doctor Who: The Husbands of River Song (2015)', 1.561683),
 ('Doctor Who: The Runaway Bride (2007)', 1.561683),
 ('Doctor Who: The Time of the Doctor (2013)', 1.561683),
 ('Doctor Who: Voyage Of The Damned (2007)', 1.561683),
 ('Kangaroo Jack (2003)', 1.561683),
 ('Safe (2012)', 1.561683)]

In [ ]:
output_list_group_3 = []
user_id_lists = [1,6,7]
for user in user_id_lists:
    recommended_movie = item_based_rec(picked_userid=user, number_of_similar_items=5, number_of_recommendations =20)
    output_list_group_3.append(recommended_movie)
output_list_group_3

[[('Valerian and the City of a Thousand Planets (2017)', 1.631481),
  ('Firewalker (1986)', 1.617744),
  ('Fist of Fury (Chinese Connection, The) (Jing wu men) (1972)', 1.617715),
  ('Crow: Salvation, The (2000)', 1.615339),
  ('Baby... Secret of the Lost Legend (1985)', 1.599267),
  ('Ant Bully, The (2006)', 1.595968),
  ('Curse of the Jade Scorpion, The (2001)', 1.59194),
  ('Deuce Bigalow: European Gigolo (2005)', 1.579533),
  ('Jackass: The Movie (2002)', 1.577884),
  ('Soul Plane (2004)', 1.575613),
  ('Swan Princess, The (1994)', 1.565838),
  ('Hustle & Flow (2005)', 1.564681),
  ('Doctor Who: Last Christmas (2014)', 1.561683),
  ('Doctor Who: The Doctor, the Widow and the Wardrobe (2011)', 1.561683),
  ('Doctor Who: The Husbands of River Song (2015)', 1.561683),
  ('Doctor Who: The Runaway Bride (2007)', 1.561683),
  ('Doctor Who: The Time of the Doctor (2013)', 1.561683),
  ('Doctor Who: Voyage Of The Damned (2007)', 1.561683),
  ('Kangaroo Jack (2003)', 1.561683),
  ('Safe (2012)', 1.561683)],
 [('Mission: Impossible - Fallout (2018)', 1.609352),
  ('Home Alone (1990)', 1.513862),
  ('Letters to Juliet (2010)', 1.496925),
  ('Jerry Maguire (1996)', 1.430246),
  ("Knight's Tale, A (2001)", 1.387576),
  ('Jaws (1975)', 1.265236),
  ('The Importance of Being Earnest (1952)', 1.242343),
  ('Blue Lagoon, The (1980)', 1.238682),
  ('Grind (2003)', 1.210677),
  ('Chronicles of Narnia: The Voyage of the Dawn Treader, The (2010)',
   1.202692),
  ('One, The (2001)', 1.173023),
  ('Young Victoria, The (2009)', 1.165252),
  ('Lean on Me (1989)', 1.159467),
  ('Hugo (2011)', 1.157741),
  ('Soul Plane (2004)', 1.147347),
  ('Thunderball (1965)', 1.146306),
  ('United 93 (2006)', 1.142498),
  ('Stepford Wives, The (2004)', 1.141778),
  ('Hot Chick, The (2002)', 1.137866),
  ('Bone Collector, The (1999)', 1.119061)],
 [("Barney's Great Adventure (1998)", 1.621275),
  ('Harmonists, The (1997)', 1.411809),
  ('High School High (1996)', 1.411204),
  ('Broken English (1996)', 1.344333),
  ('Entertaining Angels: The Dorothy Day Story (1996)', 1.344333),
  ('Cup, The (Phörpa) (1999)', 1.329315),
  ('Bean (1997)', 1.257248),
  ('Naked Gun: From the Files of Police Squad!, The (1988)', 1.25606),
  ('Colonel Chabert, Le (1994)', 1.19819),
  ('Multiplicity (1996)', 1.190844),
  ('Mystery Men (1999)', 1.181157),
  ('Desperado (1995)', 1.165691),
  ('Encino Man (1992)', 1.144377),
  ('Murder by Numbers (2002)', 1.130903),
  ('Cecil B. DeMented (2000)', 1.117525),
  ('What Planet Are You From? (2000)', 1.101971),
  ('Billy Jack Goes to Washington (1977)', 1.0972),
  ('Prom Night IV: Deliver Us From Evil (1992)', 1.0972),
  ('Slumber Party Massacre II (1987)', 1.0972),
  ('Slumber Party Massacre III (1990)', 1.0972)]]

**The original list of all 60 movies group_movies_df**

In [ ]:
group_movies_df =  pd.DataFrame([t for lst in output_list_group_3 for t in lst])
group_movies_df = group_movies_df.rename(columns={0: 'movie', 1: 'score'})
group_movies_df

                                                movie     score
0   Valerian and the City of a Thousand Planets (2...  1.631481
1                                   Firewalker (1986)  1.617744
2   Fist of Fury (Chinese Connection, The) (Jing w...  1.617715
3                         Crow: Salvation, The (2000)  1.615339
4            Baby... Secret of the Lost Legend (1985)  1.599267
5                               Ant Bully, The (2006)  1.595968
6              Curse of the Jade Scorpion, The (2001)  1.591940
7               Deuce Bigalow: European Gigolo (2005)  1.579533
8                           Jackass: The Movie (2002)  1.577884
9                                   Soul Plane (2004)  1.575613
10                          Swan Princess, The (1994)  1.565838
11                               Hustle & Flow (2005)  1.564681
12                  Doctor Who: Last Christmas (2014)  1.561683
13  Doctor Who: The Doctor, the Widow and the Ward...  1.561683
14      Doctor Who: The Husbands of River Song (2015)  1.561683
15               Doctor Who: The Runaway Bride (2007)  1.561683
16          Doctor Who: The Time of the Doctor (2013)  1.561683
17            Doctor Who: Voyage Of The Damned (2007)  1.561683
18                               Kangaroo Jack (2003)  1.561683
19                                        Safe (2012)  1.561683
20               Mission: Impossible - Fallout (2018)  1.609352
21                                  Home Alone (1990)  1.513862
22                           Letters to Juliet (2010)  1.496925
23                               Jerry Maguire (1996)  1.430246
24                            Knight's Tale, A (2001)  1.387576
25                                        Jaws (1975)  1.265236
26             The Importance of Being Earnest (1952)  1.242343
27                            Blue Lagoon, The (1980)  1.238682
28                                       Grind (2003)  1.210677
29  Chronicles of Narnia: The Voyage of the Dawn T...  1.202692
30                                    One, The (2001)  1.173023
31                         Young Victoria, The (2009)  1.165252
32                                  Lean on Me (1989)  1.159467
33                                        Hugo (2011)  1.157741
34                                  Soul Plane (2004)  1.147347
35                                 Thunderball (1965)  1.146306
36                                   United 93 (2006)  1.142498
37                         Stepford Wives, The (2004)  1.141778
38                              Hot Chick, The (2002)  1.137866
39                         Bone Collector, The (1999)  1.119061
40                    Barney's Great Adventure (1998)  1.621275
41                             Harmonists, The (1997)  1.411809
42                            High School High (1996)  1.411204
43                              Broken English (1996)  1.344333
44  Entertaining Angels: The Dorothy Day Story (1996)  1.344333
45                           Cup, The (Phörpa) (1999)  1.329315
46                                        Bean (1997)  1.257248
47  Naked Gun: From the Files of Police Squad!, Th...  1.256060
48                         Colonel Chabert, Le (1994)  1.198190
49                                Multiplicity (1996)  1.190844
50                                 Mystery Men (1999)  1.181157
51                                   Desperado (1995)  1.165691
52                                  Encino Man (1992)  1.144377
53                           Murder by Numbers (2002)  1.130903
54                           Cecil B. DeMented (2000)  1.117525
55                   What Planet Are You From? (2000)  1.101971
56               Billy Jack Goes to Washington (1977)  1.097200
57         Prom Night IV: Deliver Us From Evil (1992)  1.097200
58                   Slumber Party Massacre II (1987)  1.097200
59                  Slumber Party Massacre III (1990)  1.097200

In [ ]:
group_movies_df_drop_duplicates = group_movies_df.drop_duplicates(subset='score', keep="first")

# This is our top 20 movies for group of 3 users: user 1, 6, and 7

In [ ]:
df_mean = group_movies_df_drop_duplicates.groupby(['movie']).mean()
recommendations_for_3 = df_mean.sort_values(by=['score'], ascending=False)
recommendations_for_3.head(20)
df_top_20_movies_for_group_of_3 = recommendations_for_3.head(20)
df_top_20_movies_for_group_of_3

                                                       score
movie
Valerian and the City of a Thousand Planets (2017)  1.631481
Barney's Great Adventure (1998)                     1.621275
Firewalker (1986)                                   1.617744
Fist of Fury (Chinese Connection, The) (Jing wu...  1.617715
Crow: Salvation, The (2000)                         1.615339
Mission: Impossible - Fallout (2018)                1.609352
Baby... Secret of the Lost Legend (1985)            1.599267
Ant Bully, The (2006)                               1.595968
Curse of the Jade Scorpion, The (2001)              1.591940
Deuce Bigalow: European Gigolo (2005)               1.579533
Jackass: The Movie (2002)                           1.577884
Swan Princess, The (1994)                           1.565838
Hustle & Flow (2005)                                1.564681
Doctor Who: Last Christmas (2014)                   1.561683
Home Alone (1990)                                   1.513862
Letters to Juliet (2010)                            1.496925
Jerry Maguire (1996)                                1.430246
Harmonists, The (1997)                              1.411809
High School High (1996)                             1.411204
Knight's Tale, A (2001)                             1.387576

# Granularity Atomic Case in order to answer questions such as Why Not Matrix:
For example: Why Not Matrix:
General Cases:
1. movie name does not exist in database
2. movie name has the same score as another item
3. you asked for few items

Model Based Cases:
1. Too few of your peers have rated this movie (if num of peers <3)
2. Noone has rated this movie
3. All users have given this movie a low score (threshold score = rating of 2 * num of users ratings)

In [ ]:
def why_not(movie_name):
  #Why Not ABCXYZ:

  #General:

  tie = False
  if movie_name not in movies['title'].values:
    print("item " + movie_name + " does not exists in the database")
  if movie_name in group_movies_df["movie"].values:
    index_list = group_movies_df.index[group_movies_df['movie'] == movie_name].tolist()
    index_value = index_list[0]
    duplicate_result = group_movies_df["score"].duplicated()
    if duplicate_result[index_value] == True:
      print(movie_name + " has the same score as another item")
      tie = True
    if movie_name not in df_top_20_movies_for_group_of_3.index.values and tie == False:
      print("you asked for few items")
  #Model Based:

  #case: not many people or no one rated the movie

  movie_row = matrix_item.loc[[movie_name]]
  movie_row =  movie_row.dropna(axis=1, how='all')
  count_of_peers = movie_row.shape[1]
  if count_of_peers < 3:
    print("Too few of your peers have rated this movie")
  if count_of_peers == 0:
    print("Noone has rated this movie")
  
  #the number of ratings from users too low
  total = movie_row.sum(axis=1)
  threshold = 2 * movie_row.shape[1]
  if total < threshold:
    print("All users have given this movie a low score")

In [ ]:
why_not("Three Wishes (1995)")

Too few of your peers have rated this movie

# Position Absenteeism Case for question such as Why not rank Matrix first
1. Your peers have given a low score to this item (if the total score less than threshold of rating of 2 times number of peers in group)
2. Peer X Y Z do not like that movie (if the rating for one peer is less than 2)

In [ ]:
user_id_lists = [1,6,7]

def why_not_higher(movie_name, peer1, peer2, peer3):
  movie_row = matrix_item.loc[[movie_name]]
  movie_row =  movie_row.dropna(axis=1, how='all')
  rating1 = movie_row.loc[movie_name][peer1]
  rating2 = movie_row.loc[movie_name][peer2]
  rating3 = movie_row.loc[movie_name][peer3]
  total_rating = rating1 + rating2 + rating3
  threshold = 2 * 3
  if total_rating < threshold:
    print("your peers have given a low score to this item")
  else:
    print("Your peers love this movie")

  output_peer_string = ""
  if(rating1 < 2 or rating2 < 2 or rating3 < 2):
    if rating1 < 2:
      output_peer_string += "Peer " + peer1 + " "
    if rating2 < 2:
      output_peer_string += "Peer " + peer2 + " "
    if rating3 < 2:
      output_peer_string += "Peer " + peer3 + " "
    print(output_peer_string + " don't like that movie")

The movies we test here is not part of the top 20 recommended movie list because we are using the value from dataset containing all the movies and ratings so the same peers in top recommended movie list is not the same in "peers" for particular movie

In [ ]:
why_not_higher("Party Girl (1995)", 9, 287, 555)

Your peers love this movie

In [ ]:
df_top_20_movies_for_group_of_3.reset_index(inplace=True)
df_top_20_movies_for_group_of_3 = df_top_20_movies_for_group_of_3.rename(columns = {'index':'title'})
# df_top_20_movies_for_group_of_3.rename(columns={'movie':'title'})
df_top_20_movies_for_group_of_3.columns

Index(['movie', 'score'], dtype='object')

In [ ]:
df_top_20_movies_for_group_of_3.rename(columns = {'movie':'title'}, inplace = True)
df_top_20_movies_for_group_of_3_drop_Score = df_top_20_movies_for_group_of_3
df_top_20_movies_for_group_of_3_drop_Score.drop('score', inplace=True, axis=1)
movies_drop = movies.drop('movieId', inplace=True, axis=1)

In [ ]:
# rec_with_genres =  pd.concat([df_top_20_movies_for_group_of_3_drop_Score, movies])
rec_with_genres = pd.merge(df_top_20_movies_for_group_of_3_drop_Score, movies, on = 'title', how='inner')

In [ ]:
rec_with_genres.head(20)

,title,genres
0,Valerian and the City of a Thousand Planets (2...,Action|Adventure|Sci-Fi
1,Barney's Great Adventure (1998),Adventure|Children
2,Firewalker (1986),Adventure
3,"Fist of Fury (Chinese Connection, The) (Jing w...",Action|Drama|Romance|Thriller
4,"Crow: Salvation, The (2000)",Action|Horror
5,Mission: Impossible - Fallout (2018),Action|Adventure|Thriller
6,Baby... Secret of the Lost Legend (1985),Adventure|Sci-Fi
7,"Ant Bully, The (2006)",Adventure|Animation|Children|Comedy|Fantasy|IMAX
8,"Curse of the Jade Scorpion, The (2001)",Comedy
9,Deuce Bigalow: European Gigolo (2005),Comedy
10,Jackass: The Movie (2002),Action|Comedy|Documentary
11,"Swan Princess, The (1994)",Animation|Children
12,Hustle & Flow (2005),Crime|Drama
13,Doctor Who: Last Christmas (2014),Adventure|Drama|Fantasy|Sci-Fi
14,Home Alone (1990),Children|Comedy
15,Letters to Juliet (2010),Drama|Romance
16,Jerry Maguire (1996),Drama|Romance
17,"Harmonists, The (1997)",Drama
18,High School High (1996),Comedy
19,"Knight's Tale, A (2001)",Action|Comedy|Romance

# Granularity Group case to answer questions such as Why No Comedies
2 cases:
1. Your peers dislike that genre (if none of the movies in recommended movies list for group has that genre)
2. Only x of your peers like that genre (if less than 5 peers like that movie of that genre)

In [ ]:
def why_no_genre(genre):
  genre_list = rec_with_genres['genres'].tolist()
  genre_substring = genre
  found = 0
  for genres in genre_list:
    if genre_substring in genres:
      found = found + 1
  if found == 0:
    print("Your peers dislike " + genre)
  elif found < 5:
    print("Only " + str(found) + " of your peers like " + genre)

In [ ]:
why_no_genre("Musical")

Your peers dislike Musical